CREATE TABLE IF NOT EXISTS schools (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  schoolName VARCHAR(100) DEFAULT NULL,
  city  VARCHAR(100) DEFAULT NULL,
  states VARCHAR(100) DEFAULT NULL
  


) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


