CREATE TABLE IF NOT EXISTS `actors` (
`id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
`firstname` VARCHAR(250) NOT NULL,
`lastname` VARCHAR(250) NOT NULL, 
`dob` VARCHAR(25) NOT NULL, 
`height` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;


